// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'introduction',
    'quickstart',
    'installation',
    {
      type: 'category',
      label: 'Defining Workflows',
      link: {
        type: 'generated-index',
        description: 'Author workflow and activity classes, payloads, identifiers, and status handling.',
      },
      items: [
        'defining-workflows/workflows',
        'defining-workflows/activities',
        'defining-workflows/starting-workflows',
        'defining-workflows/passing-data',
        'defining-workflows/workflow-id',
        'defining-workflows/workflow-status',
        'defining-workflows/workflow-api',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
        description: 'Choose message streams, durable commands, waits, retries, versioning, and bounded-history patterns.',
      },
      items: [
        'features/message-streams',
        'features/signals',
        'features/updates',
        'features/queries',
        'features/signal+timer',
        'features/timers',
        'features/condition-waits',
        'features/timeouts',
        'features/continue-as-new',
        'features/side-effects',
        'features/concurrency',
        'features/sagas',
        'features/child-workflows',
        'features/cancel-and-terminate',
        'features/heartbeats',
        'features/schedules',
        'features/search-attributes',
        'features/memo',
        'features/events',
        'features/versioning',
        'features/external-payload-storage',
        'features/activity-execution-model',
        'features/local-activities',
        'features/worker-sessions',
        'features/sticky-execution',
      ],
    },
    {
      type: 'category',
      label: 'Constraints',
      link: {
        type: 'generated-index',
        description: 'Understand deterministic workflow boundaries and structural limits.',
      },
      items: [
        'constraints/overview',
        'constraints/execution-guarantees',
        'constraints/workflow-constraints',
        'constraints/activity-constraints',
        'constraints/constraints-summary',
        'constraints/structural-limits',
      ],
    },
    'how-it-works',
    'testing',
    {
      type: 'category',
      label: 'Run And Operate',
      link: {
        type: 'generated-index',
        description: 'Deploy, observe, diagnose, recover, and support running workflow fleets.',
      },
      items: [
        'deployment',
        'rolling-upgrades',
        'monitoring',
        'operator-operating-envelope',
        'waterline-operator-api',
        'compatibility',
        'platform-protocol-specs',
        'platform-conformance',
        'docs-page-release-audit',
        'sdk-neutrality',
        'failures-and-recovery',
        'support',
        'migration',
        'sample-app',
        'contribute-a-sample',
        {
          type: 'category',
          label: 'Configuration',
          link: {
            type: 'generated-index',
            description: 'Configure storage, connections, namespaces, service boundaries, and retention.',
          },
          items: [
            'configuration/publishing-config',
            'configuration/options',
            'configuration/ensuring-same-server',
            'configuration/database-connection',
            'configuration/customization-matrix',
            'configuration/microservices',
            'configuration/pruning-workflows',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Control Plane And Polyglot',
      link: {
        type: 'generated-index',
        description: 'Use the server, CLI, Python SDK, and shared control-plane contracts.',
      },
      items: [
        'polyglot/server',
        'polyglot/deployment-modes',
        'polyglot/cloud-control-plane',
        'polyglot/server-config-reference',
        'polyglot/server-api-reference',
        'polyglot/server-role-topology',
        'polyglot/namespace-auth-workers',
        'polyglot/worker-compatibility-routing',
        'polyglot/embedded-to-server',
        'polyglot/cli',
        'polyglot/cli-reference',
        'polyglot/python',
        'polyglot/cli-python-parity',
        'polyglot/rust',
      ],
    },
    {
      type: 'category',
      label: 'External Execution And Ingress',
      link: {
        type: 'generated-index',
        description: 'Expose HTTP ingress, external workers, task queues, and protocol-level integrations.',
      },
      items: [
        'polyglot/external-execution',
        'polyglot/invocable-carrier',
        'polyglot/invocable-php-handler',
        'polyglot/worker-protocol',
        'polyglot/task-matching-dispatch',
        'polyglot/task-queue-admission',
        'polyglot/worker-build-id-rollout',
        'features/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'AI And Automation',
      link: {
        type: 'generated-index',
        description: 'Give coding agents and automation stable docs, manifests, commands, and workflow tools.',
      },
      items: [
        'ai-assisted-development',
        'agent-operating-loop',
        'mcp-workflows',
        'agent-tooling-contract',
      ],
    },
    'sponsors',
  ],
};

module.exports = sidebars;
