// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'introduction',
    'quickstart',
    'capabilities',
    'laravel-adoption',
    {
      type: 'category',
      label: 'Service Mode',
      link: {
        type: 'generated-index',
        description: 'Connect first-party PHP, Python, or Rust clients and workers to Durable Workflow Cloud or a self-hosted Server. Cloud includes Managed Waterline; self-hosted operators deploy Waterline separately against a Server-owned namespace.',
      },
      items: [
        'polyglot/deployment-modes',
        'polyglot/cloud-control-plane',
        'polyglot/server',
        'polyglot/workflow-streams',
        {
          type: 'category',
          label: 'CLI',
          link: {
            type: 'generated-index',
            description: 'Install the dw operator client and look up its complete command surface.',
          },
          items: [
            'polyglot/cli',
            'polyglot/cli-reference',
          ],
        },
        {
          type: 'category',
          label: 'SDKs',
          link: {
            type: 'generated-index',
            description: 'Build service-mode clients and workers with the first-party PHP, Python, and Rust SDKs.',
          },
          items: [
            'polyglot/php',
            'polyglot/python',
            'polyglot/rust',
          ],
        },
        'polyglot/cli-python-parity',
        'polyglot/server-config-reference',
        'polyglot/server-api-reference',
        'polyglot/server-role-topology',
        'polyglot/namespace-auth-workers',
        'polyglot/worker-compatibility-routing',
        'polyglot/embedded-to-server',
      ],
    },
    {
      type: 'category',
      label: 'Embedded',
      link: {
        type: 'generated-index',
        description: 'Install, author, test, and configure workflows with the in-application Laravel runtime.',
      },
      items: [
        'installation',
        {
          type: 'category',
          label: 'Defining Workflows',
          link: {
            type: 'generated-index',
            description: 'Author workflow and activity classes, payloads, identifiers, and status handling for the in-application Laravel runtime.',
          },
          items: [
            'defining-workflows/workflows',
            'defining-workflows/activities',
            'defining-workflows/starting-workflows',
            'defining-workflows/passing-data',
            'defining-workflows/workflow-id',
            'defining-workflows/workflow-status',
            'defining-workflows/workflow-api',
          ],
        },
        {
          type: 'category',
          label: 'Features',
          link: {
            type: 'generated-index',
            description: 'Choose message streams, durable commands, waits, retries, versioning, and bounded-history patterns for the in-application Laravel runtime.',
          },
          items: [
            'features/signals',
            'features/updates',
            'features/queries',
            'features/signal+timer',
            'features/timers',
            'features/condition-waits',
            'features/timeouts',
            'features/continue-as-new',
            'features/side-effects',
            'features/concurrency',
            'features/sagas',
            'features/child-workflows',
            'features/cancel-and-terminate',
            'features/heartbeats',
            'features/schedules',
            'features/search-attributes',
            'features/memo',
            'features/message-streams',
            'features/events',
            'features/versioning',
            'features/external-payload-storage',
            'features/activity-execution-model',
            'features/portable-worker-affinity',
            'features/local-activities',
            'features/worker-sessions',
            'features/sticky-execution',
            'features/webhooks',
          ],
        },
        {
          type: 'category',
          label: 'Constraints',
          link: {
            type: 'generated-index',
            description: 'Understand deterministic workflow boundaries and structural limits for the in-application Laravel runtime.',
          },
          items: [
            'constraints/overview',
            'constraints/idempotent-vs-deterministic',
            'constraints/execution-guarantees',
            'constraints/workflow-constraints',
            'constraints/activity-constraints',
            'constraints/constraints-summary',
            'constraints/structural-limits',
          ],
        },
        'how-it-works',
        'testing',
        'failures-and-recovery',
        'migration',
        {
          type: 'category',
          label: 'Configuration',
          link: {
            type: 'generated-index',
            description: 'Configure storage, connections, service boundaries, and retention for the in-application Laravel runtime.',
          },
          items: [
            'configuration/publishing-config',
            'configuration/options',
            'configuration/ensuring-same-server',
            'configuration/database-connection',
            'configuration/customization-matrix',
            'configuration/microservices',
            'configuration/pruning-workflows',
          ],
        },
        'sample-app',
        'contribute-a-sample',
      ],
    },
    {
      type: 'category',
      label: 'Run And Operate',
      link: {
        type: 'generated-index',
        description: 'Deploy, observe, diagnose, recover, and support running workflow fleets.',
      },
      items: [
        'deployment',
        'rolling-upgrades',
        'monitoring',
        'operator-operating-envelope',
        'waterline-operator-api',
        'compatibility',
        'platform-protocol-specs',
        'platform-conformance',
        'docs-page-release-audit',
        'sdk-neutrality',
        'support',
      ],
    },
    {
      type: 'category',
      label: 'External Execution And Ingress',
      link: {
        type: 'generated-index',
        description: 'Expose HTTP ingress, external workers, task queues, and protocol-level integrations.',
      },
      items: [
        'polyglot/external-execution',
        'polyglot/invocable-carrier',
        'polyglot/invocable-php-handler',
        'polyglot/worker-protocol',
        'polyglot/avro-value-protocol',
        'polyglot/prerelease-history-migration',
        'polyglot/task-matching-dispatch',
        'polyglot/task-queue-admission',
        'polyglot/worker-build-id-rollout',
      ],
    },
    {
      type: 'category',
      label: 'AI And Automation',
      link: {
        type: 'generated-index',
        description: 'Give coding agents and automation stable docs, manifests, commands, and workflow tools.',
      },
      items: [
        'ai-agent-workflow-engine',
        'ai-assisted-development',
        'agent-operating-loop',
        'mcp-workflows',
        'agent-tooling-contract',
      ],
    },
    'sponsors',
  ],
};

module.exports = sidebars;
