externalDatabase:
  host: mysql.durable-workflow.svc.cluster.local
  auth:
    username: durable_workflow
    password: durable_workflow

externalRedis:
  host: redis.durable-workflow.svc.cluster.local

auth:
  serverKey: "base64:bm90LWEtc2VjcmV0"
  workerToken: not-a-secret
  operatorToken: not-a-secret
  adminToken: not-a-secret

server:
  replicaCount: 1
  pdb:
    enabled: false

worker:
  replicaCount: 1
