#!/usr/bin/env node

const assert = require('assert');
const childProcess = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  REQUIRED_DISCOVERY_ENTRIES,
  assertCompleteGitHistory,
  assertSitemapFreshness,
  blockLastmod,
  blockLocation,
  buildRequiredDiscoveryEntries,
  buildSourceRouteMap,
  collectRenderingDependencies,
  gitModificationDate,
  isW3cDate,
  patchContentRouteFreshness,
  patchDiscoveryEntries,
  sitemapBlocks,
} = require('./patch-public-discovery-sitemap');
const platformConformanceContract = require('../static/platform-conformance-contract.json');
const {llmSourceHistoryPathspecs} = require('./llms-source-inventory');

const siteUrl = 'https://durable-workflow.com';

function urlEntry(route, lastmod = '2026-08-01') {
  return (
    `<url><loc>${siteUrl}${route}</loc><lastmod>${lastmod}</lastmod>` +
      '<changefreq>weekly</changefreq><priority>0.5</priority></url>'
  );
}

function urlset(entries) {
  return (
    '<?xml version="1.0" encoding="UTF-8"?>' +
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
      entries.join('') +
      '</urlset>'
  );
}

function freshnessMap(sitemap) {
  return new Map(sitemapBlocks(sitemap).map(({block}) => [
    new URL(blockLocation(block)).pathname,
    blockLastmod(block),
  ]));
}

assert(isW3cDate('2026-08-09'), 'a real calendar date must be valid W3C date syntax');
assert(!isW3cDate('2026-8-9'), 'non-padded dates must be rejected');
assert(!isW3cDate('2026-02-30'), 'impossible calendar dates must be rejected');

assert.doesNotThrow(
  () => assertCompleteGitHistory({git: () => 'false'}),
  'a complete checkout must support source-derived freshness',
);
assert.throws(
  () => assertCompleteGitHistory({git: () => 'true'}),
  /fetch-depth: 0/,
  'a shallow checkout must fail instead of assigning one deploy date to every route',
);

let requestedGitArgs;
assert.strictEqual(
  gitModificationDate(['docs/introduction.md'], {
    git: args => {
      requestedGitArgs = args;
      return '2026-08-09T18:13:44Z';
    },
  }),
  '2026-08-09',
  'source timestamps must be normalized to stable W3C dates',
);
assert.deepStrictEqual(
  requestedGitArgs,
  ['log', '-1', '--format=%cI', '--', 'docs/introduction.md'],
  'route freshness must query only the route source dependency set',
);

const sourceRoutes = buildSourceRouteMap();
assert.strictEqual(
  sourceRoutes.get('/docs/2.0/introduction'),
  'docs/introduction.md',
  'the 2.0 introduction route must resolve to its actual Markdown source',
);
assert.strictEqual(
  sourceRoutes.get('/docs/2.0/quickstart'),
  'docs/quickstart.md',
  'the 2.0 quickstart route must resolve to its actual Markdown source',
);
const serviceModeCategorySources = sourceRoutes.get(
  '/docs/2.0/category/service-mode',
);
assert(
  Array.isArray(serviceModeCategorySources) &&
    serviceModeCategorySources.includes('sidebars.js'),
  'generated category routes must resolve to the sidebar that defines their content',
);
const stableFeaturesCategorySources = sourceRoutes.get('/docs/category/features');
assert(
  Array.isArray(stableFeaturesCategorySources) &&
    stableFeaturesCategorySources.includes(
      'versioned_docs/version-1.x/features/_category_.json',
    ) &&
    stableFeaturesCategorySources.includes(
      'versioned_sidebars/version-1.x-sidebars.json',
    ),
  'stable autogenerated category routes must resolve to category metadata and sidebar sources',
);
assert(
  !stableFeaturesCategorySources.includes(
    'versioned_docs/version-1.x/configuration/options.md',
  ),
  'stable category routes must exclude documentation sources from unrelated categories',
);
const workflowTagSources = sourceRoutes.get('/blog/tags/workflow');
assert(
  Array.isArray(workflowTagSources) &&
    workflowTagSources.includes(
      'blog/2026-05-08-learning-durable-workflow-from-the-sample-app.md',
    ),
  'blog tag routes must resolve to posts carrying that tag',
);
assert(
  !workflowTagSources.includes('blog/2022-10-29-email-verifications.md'),
  'blog tag routes must exclude posts carrying unrelated tags',
);

const introductionDependencies = collectRenderingDependencies('docs/introduction.md');
assert(
  introductionDependencies.has('scripts/published-artifact-versions.json'),
  'rendered artifact tokens must bind route freshness to the published version authority',
);
const quickstartDependencies = collectRenderingDependencies('docs/quickstart.md');
assert(
  quickstartDependencies.has('src/components/QualifiedArtifactTuple/index.js'),
  'rendered component source must participate in quickstart freshness',
);
assert(
  quickstartDependencies.has('static/public-artifact-compatibility-evidence.json'),
  'transitive structured component authority must participate in quickstart freshness',
);

const generatedEntries = buildRequiredDiscoveryEntries(platformConformanceContract);
for (const route of [
  '/llms.txt',
  '/llms-full-2.0.txt',
  '/quickstart-execution-contract.json',
  '/platform-conformance/run-ledger.json',
]) {
  assert(
    generatedEntries.some(entry => entry.path === route),
    `generated discovery inventory must include ${route}`,
  );
}
assert.deepStrictEqual(
  generatedEntries.map(entry => entry.path),
  REQUIRED_DISCOVERY_ENTRIES.map(entry => entry.path),
  'the tested discovery inventory must match the production patch inventory',
);

const compactLlmRoutes = ['/llms.txt', '/llms-1.x.txt', '/llms-2.0.txt'];
const fullLlmRoutes = [
  '/llms-full.txt',
  '/llms-full-1.x.txt',
  '/llms-full-2.0.txt',
  '/2.0/llms-full.txt',
];
const llmEntries = generatedEntries.filter(entry =>
  [...compactLlmRoutes, ...fullLlmRoutes].includes(entry.path),
);
const excludedLlmSources = [
  'docs/sponsors.md',
  'docs/support.md',
  'versioned_docs/version-1.x/sponsors.md',
  'versioned_docs/version-1.x/support.md',
];

for (const entry of llmEntries) {
  const isCompact = compactLlmRoutes.includes(entry.path);
  const allSources = [...entry.sourcePaths, ...entry.sourceHistoryPathspecs];
  const contentSourceRoot = entry.path.includes('2.0')
    ? 'docs'
    : 'versioned_docs/version-1.x';
  assert.strictEqual(
    entry.sourcePaths.includes('scripts/generate-llms.js'),
    isCompact,
    `${entry.path} freshness must track the compact generator only when it renders that route`,
  );
  assert.strictEqual(
    entry.sourcePaths.includes('scripts/generate-llms-full.js'),
    !isCompact,
    `${entry.path} freshness must track the full generator only when it renders that route`,
  );
  assert(
    entry.sourceHistoryPathspecs.some(sourcePath => sourcePath.endsWith('/**/*.md')) &&
      entry.sourceHistoryPathspecs.some(sourcePath => sourcePath.endsWith('/**/*.mdx')),
    `${entry.path} freshness must track renderable documentation throughout Git history`,
  );
  assert(
    entry.sourceHistoryPathspecs.some(sourcePath => sourcePath.endsWith('/**/_category_.json')),
    `${entry.path} freshness must track category metadata throughout Git history`,
  );
  for (const excludedSource of excludedLlmSources) {
    assert(
      !allSources.includes(excludedSource),
      `${entry.path} freshness must exclude ${excludedSource} because it is not rendered`,
    );
  }
  for (const basename of ['sponsors.md', 'support.md']) {
    assert(
      allSources.includes(`:(exclude,glob)${contentSourceRoot}/**/${basename}`),
      `${entry.path} freshness must exclude ${basename} throughout Git history`,
    );
  }
}

function llmFreshness({
  compact = '2026-08-10',
  full = '2026-08-10',
  v1Content = '2026-08-09',
  v2Content = '2026-08-09',
  excluded = '2026-08-09',
} = {}) {
  return freshnessMap(patchDiscoveryEntries(urlset([]), llmEntries, {
    modificationDate: sourcePaths => {
      const dates = ['2026-08-08'];
      if (sourcePaths.some(sourcePath => sourcePath.startsWith(':(glob)docs/'))) {
        dates.push(v2Content);
      }
      if (
        sourcePaths.some(sourcePath =>
          sourcePath.startsWith(':(glob)versioned_docs/version-1.x/'),
        )
      ) {
        dates.push(v1Content);
      }
      if (
        sourcePaths.some(sourcePath => excludedLlmSources.includes(sourcePath)) ||
        sourcePaths.includes('docs') ||
        sourcePaths.includes('versioned_docs/version-1.x')
      ) {
        dates.push(excluded);
      }
      if (sourcePaths.includes('scripts/generate-llms-full.js')) {
        dates.push(full);
      }
      if (sourcePaths.includes('scripts/generate-llms.js')) {
        dates.push(compact);
      }
      return dates.sort().at(-1);
    },
  }));
}

function runFixtureGit(repoRoot, args, date) {
  return childProcess.execFileSync('git', args, {
    cwd: repoRoot,
    encoding: 'utf8',
    env: date
      ? {
          ...process.env,
          GIT_AUTHOR_DATE: `${date}T12:00:00Z`,
          GIT_COMMITTER_DATE: `${date}T12:00:00Z`,
        }
      : process.env,
  }).trim();
}

function commitFixture(repoRoot, message, date) {
  runFixtureGit(repoRoot, ['add', '-A']);
  runFixtureGit(
    repoRoot,
    [
      '-c',
      'user.name=LLM freshness test',
      '-c',
      'user.email=test@example.com',
      'commit',
      '-m',
      message,
    ],
    date,
  );
}

const historyFixture = fs.mkdtempSync(path.join(os.tmpdir(), 'llm-freshness-history-'));
try {
  runFixtureGit(historyFixture, ['init', '--quiet']);
  fs.mkdirSync(path.join(historyFixture, 'docs', 'guide'), {recursive: true});
  fs.writeFileSync(path.join(historyFixture, 'docs', 'guide', 'page.md'), '# Guide\n');
  fs.writeFileSync(
    path.join(historyFixture, 'docs', 'guide', '_category_.json'),
    '{"label":"Guide"}\n',
  );
  fs.writeFileSync(path.join(historyFixture, 'docs', 'support.md'), '# Support\n');
  commitFixture(historyFixture, 'Add rendered and excluded documentation', '2026-08-09');

  const historyPathspecs = llmSourceHistoryPathspecs('docs');
  const fixtureModificationDate = () => gitModificationDate(historyPathspecs, {
    repoRoot: historyFixture,
  });
  assert.strictEqual(
    fixtureModificationDate(),
    '2026-08-09',
    'included source additions must establish LLM freshness',
  );

  fs.writeFileSync(path.join(historyFixture, 'docs', 'support.md'), '# Revised support\n');
  commitFixture(historyFixture, 'Change excluded documentation', '2026-08-10');
  assert.strictEqual(
    fixtureModificationDate(),
    '2026-08-09',
    'changing an excluded document must preserve LLM freshness',
  );

  fs.rmSync(path.join(historyFixture, 'docs', 'support.md'));
  commitFixture(historyFixture, 'Delete excluded documentation', '2026-08-11');
  assert.strictEqual(
    fixtureModificationDate(),
    '2026-08-09',
    'deleting an excluded document must preserve LLM freshness',
  );

  fs.rmSync(path.join(historyFixture, 'docs', 'guide', 'page.md'));
  commitFixture(historyFixture, 'Delete rendered documentation', '2026-08-12');
  assert.strictEqual(
    fixtureModificationDate(),
    '2026-08-12',
    'deleting a rendered document must advance LLM freshness',
  );

  fs.writeFileSync(path.join(historyFixture, 'docs', 'guide', 'page.md'), '# Guide restored\n');
  commitFixture(historyFixture, 'Restore rendered documentation', '2026-08-13');
  fs.rmSync(path.join(historyFixture, 'docs', 'guide', '_category_.json'));
  commitFixture(historyFixture, 'Delete rendered category metadata', '2026-08-14');
  assert.strictEqual(
    fixtureModificationDate(),
    '2026-08-14',
    'deleting rendered category metadata must advance LLM freshness',
  );
} finally {
  fs.rmSync(historyFixture, {recursive: true, force: true});
}

const baselineLlmFreshness = llmFreshness();
const fullGeneratorChange = llmFreshness({full: '2026-08-11'});
for (const route of compactLlmRoutes) {
  assert.strictEqual(
    fullGeneratorChange.get(route),
    baselineLlmFreshness.get(route),
    `a full-generator-only change must preserve ${route} freshness`,
  );
}
for (const route of fullLlmRoutes) {
  assert.strictEqual(
    fullGeneratorChange.get(route),
    '2026-08-11',
    `a full-generator-only change must advance ${route} freshness`,
  );
}

const compactGeneratorChange = llmFreshness({compact: '2026-08-12'});
for (const route of compactLlmRoutes) {
  assert.strictEqual(
    compactGeneratorChange.get(route),
    '2026-08-12',
    `a compact-generator-only change must advance ${route} freshness`,
  );
}
for (const route of fullLlmRoutes) {
  assert.strictEqual(
    compactGeneratorChange.get(route),
    baselineLlmFreshness.get(route),
    `a compact-generator-only change must preserve ${route} freshness`,
  );
}

const excludedContentChange = llmFreshness({excluded: '2026-08-13'});
for (const route of [...compactLlmRoutes, ...fullLlmRoutes]) {
  assert.strictEqual(
    excludedContentChange.get(route),
    baselineLlmFreshness.get(route),
    `an excluded documentation change must preserve ${route} freshness`,
  );
}

const v1ContentRoutes = ['/llms.txt', '/llms-full.txt', '/llms-1.x.txt', '/llms-full-1.x.txt'];
const v2ContentRoutes = ['/llms-2.0.txt', '/llms-full-2.0.txt', '/2.0/llms-full.txt'];
const v1ContentChange = llmFreshness({v1Content: '2026-08-13'});
for (const route of v1ContentRoutes) {
  assert.strictEqual(
    v1ContentChange.get(route),
    '2026-08-13',
    `a real stable documentation change must advance ${route} freshness`,
  );
  assert(isW3cDate(v1ContentChange.get(route)), `${route} freshness must be a valid W3C date`);
}
for (const route of v2ContentRoutes) {
  assert.strictEqual(
    v1ContentChange.get(route),
    baselineLlmFreshness.get(route),
    `a stable documentation change must preserve ${route} freshness`,
  );
}

const v2ContentChange = llmFreshness({v2Content: '2026-08-14'});
for (const route of v2ContentRoutes) {
  assert.strictEqual(
    v2ContentChange.get(route),
    '2026-08-14',
    `a real prerelease documentation change must advance ${route} freshness`,
  );
  assert(isW3cDate(v2ContentChange.get(route)), `${route} freshness must be a valid W3C date`);
}
for (const route of v1ContentRoutes) {
  assert.strictEqual(
    v2ContentChange.get(route),
    baselineLlmFreshness.get(route),
    `a prerelease documentation change must preserve ${route} freshness`,
  );
}

const baseSitemap = urlset([
  urlEntry('/docs/introduction/'),
  urlEntry('/docs/2.0/introduction/'),
  urlEntry('/docs/2.0/quickstart/'),
  urlEntry('/blog/learning-durable-workflow/'),
  urlEntry('/independent-route/'),
]);
const sourceDates = new Map([
  ['versioned_docs/version-1.x/introduction.md', '2026-08-08'],
  ['docs/introduction.md', '2026-08-08'],
  ['docs/quickstart.md', '2026-08-08'],
  ['scripts/published-artifact-versions.json', '2026-08-09'],
  ['static/quickstart-execution-contract.json', '2026-08-07'],
]);
const modificationDate = sourcePaths => {
  return sourcePaths
    .map(sourcePath => sourceDates.get(sourcePath) || '2026-08-01')
    .sort()
    .at(-1);
};
const withContentFreshness = patchContentRouteFreshness(baseSitemap, {
  modificationDate,
  routeSources: new Map([
    ['/docs/introduction', 'versioned_docs/version-1.x/introduction.md'],
    ['/docs/2.0/introduction', 'docs/introduction.md'],
    ['/docs/2.0/quickstart', 'docs/quickstart.md'],
  ]),
});
const fixtureDiscoveryEntries = [{
  path: '/generated-discovery.json',
  buildPath: 'generated-discovery.json',
  sourcePaths: ['static/quickstart-execution-contract.json'],
}];
const firstDeploy = patchDiscoveryEntries(withContentFreshness, fixtureDiscoveryEntries, {
  modificationDate,
});
const firstDates = freshnessMap(firstDeploy);

assert.strictEqual(
  firstDates.get('/docs/2.0/introduction/'),
  '2026-08-09',
  'a changed structured rendering authority must advance the introduction freshness',
);
assert.strictEqual(
  firstDates.get('/docs/2.0/quickstart/'),
  '2026-08-09',
  'a changed structured rendering dependency must advance its route freshness',
);
assert.strictEqual(
  firstDates.get('/docs/introduction/'),
  '2026-08-08',
  'a changed Markdown source must advance its route freshness',
);
assert.strictEqual(
  firstDates.get('/independent-route/'),
  '2026-08-01',
  'an unrelated route must retain its prior modification date',
);
assert.strictEqual(
  firstDates.get('/generated-discovery.json'),
  '2026-08-07',
  'generated public discovery must carry its own source-derived freshness',
);

const unrelatedRedeploy = patchDiscoveryEntries(
  patchContentRouteFreshness(baseSitemap, {
    modificationDate,
    routeSources: new Map([
      ['/docs/introduction', 'versioned_docs/version-1.x/introduction.md'],
      ['/docs/2.0/introduction', 'docs/introduction.md'],
      ['/docs/2.0/quickstart', 'docs/quickstart.md'],
    ]),
  }),
  fixtureDiscoveryEntries,
  {modificationDate},
);
assert.strictEqual(
  unrelatedRedeploy,
  firstDeploy,
  'an unrelated deploy with unchanged source dates must produce byte-stable freshness metadata',
);

const sidebarOnlyDeploy = patchContentRouteFreshness(
  urlset([
    urlEntry('/docs/2.0/category/service-mode/'),
    urlEntry('/docs/2.0/introduction/', '2026-08-09'),
    urlEntry('/independent-route/'),
  ]),
  {
    routeSources: sourceRoutes,
    modificationDate: sourcePaths =>
      sourcePaths.includes('sidebars.js') ? '2026-08-10' : '2026-08-09',
  },
);
const sidebarOnlyDates = freshnessMap(sidebarOnlyDeploy);
assert.strictEqual(
  sidebarOnlyDates.get('/docs/2.0/category/service-mode/'),
  '2026-08-10',
  'a sidebar-only change must advance the generated category route it defines',
);
assert.strictEqual(
  sidebarOnlyDates.get('/docs/2.0/introduction/'),
  '2026-08-09',
  'a sidebar-only change must not advance an unchanged documentation source route',
);
assert.strictEqual(
  sidebarOnlyDates.get('/independent-route/'),
  '2026-08-01',
  'a sidebar-only change must preserve unrelated route freshness',
);

const stableCategoryDeploy = patchContentRouteFreshness(
  urlset([
    urlEntry('/docs/category/features/'),
    urlEntry('/docs/category/configuration/'),
    urlEntry('/docs/2.0/introduction/', '2026-08-09'),
  ]),
  {
    routeSources: sourceRoutes,
    modificationDate: sourcePaths =>
      sourcePaths.includes('versioned_docs/version-1.x/features/_category_.json')
        ? '2026-08-11'
        : '2026-08-09',
  },
);
const stableCategoryDates = freshnessMap(stableCategoryDeploy);
assert.strictEqual(
  stableCategoryDates.get('/docs/category/features/'),
  '2026-08-11',
  'a stable category metadata change must advance its generated index route',
);
assert.strictEqual(
  stableCategoryDates.get('/docs/category/configuration/'),
  '2026-08-09',
  'a stable category metadata change must not advance a sibling category route',
);
assert.strictEqual(
  stableCategoryDates.get('/docs/2.0/introduction/'),
  '2026-08-09',
  'a stable category metadata change must preserve unrelated documentation routes',
);

const changedTagPost =
  'blog/2026-05-08-learning-durable-workflow-from-the-sample-app.md';
const blogTagDeploy = patchContentRouteFreshness(
  urlset([
    urlEntry('/blog/tags/workflow/'),
    urlEntry('/blog/tags/workflow/page/2/'),
    urlEntry('/blog/tags/sample-app/'),
    urlEntry('/blog/tags/ai/'),
  ]),
  {
    routeSources: sourceRoutes,
    modificationDate: sourcePaths =>
      sourcePaths.includes(changedTagPost) ? '2026-08-12' : '2026-08-09',
  },
);
const blogTagDates = freshnessMap(blogTagDeploy);
assert.strictEqual(
  blogTagDates.get('/blog/tags/workflow/'),
  '2026-08-12',
  'a changed post must advance every generated tag route containing that post',
);
assert.strictEqual(
  blogTagDates.get('/blog/tags/workflow/page/2/'),
  '2026-08-12',
  'tag pagination routes must use the same tag-specific source set',
);
assert.strictEqual(
  blogTagDates.get('/blog/tags/sample-app/'),
  '2026-08-12',
  'a changed post must advance each of its tag indexes',
);
assert.strictEqual(
  blogTagDates.get('/blog/tags/ai/'),
  '2026-08-09',
  'a changed post must not advance an unrelated tag route',
);

const originalInventory = new Set(
  sitemapBlocks(baseSitemap).map(({block}) => blockLocation(block)),
);
const patchedInventory = new Set(
  sitemapBlocks(firstDeploy).map(({block}) => blockLocation(block)),
);
for (const location of originalInventory) {
  assert(patchedInventory.has(location), `sitemap patch must preserve canonical route ${location}`);
}
assert.strictEqual(
  patchedInventory.size,
  originalInventory.size + fixtureDiscoveryEntries.length,
  'sitemap patch may add only the declared generated discovery inventory',
);
assert.doesNotThrow(
  () => assertSitemapFreshness(firstDeploy, fixtureDiscoveryEntries),
  'all documentation, blog, and generated discovery entries must have valid dates',
);

console.log('Public discovery sitemap freshness tests passed');
